<a href="https://colab.research.google.com/github/Varun1299/Spectral-Clustering/blob/master/Spectral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import networkx as nx
import numpy as np

In [0]:
G=nx.Graph()

In [0]:
G.add_edge(1,2)
G.add_edge(1,3)
G.add_edge(3,2)
G.add_edge(6,5)
G.add_edge(6,4)
G.add_edge(4,5)

In [18]:
G.nodes

NodeView((1, 2, 3, 6, 5, 4))

In [0]:
A = nx.adjacency_matrix(G)

In [20]:
print(A.todense())

[[0 1 1 0 0 0]
 [1 0 1 0 0 0]
 [1 1 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]]


In [0]:
D = np.zeros((len(G.nodes), len(G.nodes)))  

In [22]:
indexer = 0
for node in G.nodes:
  D[indexer][indexer] = G.degree(node)
  indexer += 1
print(D)
print(G.degree(6))

[[2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2.]]
2


In [0]:
L = D - A

In [24]:
L

matrix([[ 2., -1., -1.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  0.,  0.],
        [-1., -1.,  2.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2., -1., -1.],
        [ 0.,  0.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0., -1., -1.,  2.]])

In [0]:
for rowidx in range(L.shape[0]):
  L[rowidx] = L[rowidx]/float(L.item(rowidx, rowidx))

In [26]:
L

matrix([[ 1. , -0.5, -0.5,  0. ,  0. ,  0. ],
        [-0.5,  1. , -0.5,  0. ,  0. ,  0. ],
        [-0.5, -0.5,  1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  1. , -0.5, -0.5],
        [ 0. ,  0. ,  0. , -0.5,  1. , -0.5],
        [ 0. ,  0. ,  0. , -0.5, -0.5,  1. ]])

In [27]:
L.item((1,1))

1.0

In [0]:
eigvals,eigvecs = np.linalg.eig(L)

In [29]:
eigvecs

matrix([[ 0.81649658, -0.57735027,  0.29329423,  0.        ,  0.        ,
          0.        ],
        [-0.40824829, -0.57735027, -0.80655913,  0.        ,  0.        ,
          0.        ],
        [-0.40824829, -0.57735027,  0.5132649 ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.81649658, -0.57735027,
          0.29329423],
        [ 0.        ,  0.        ,  0.        , -0.40824829, -0.57735027,
         -0.80655913],
        [ 0.        ,  0.        ,  0.        , -0.40824829, -0.57735027,
          0.5132649 ]])

In [30]:
eigvals

array([ 1.50000000e+00, -1.11022302e-16,  1.50000000e+00,  1.50000000e+00,
       -1.11022302e-16,  1.50000000e+00])