<a href="https://colab.research.google.com/github/Varun1299/Spectral-Clustering/blob/master/Spectral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import networkx as nx
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import math

In [0]:
G=nx.Graph()

In [0]:
G.add_edge(1,2)
G.add_edge(1,3)
G.add_edge(3,2)
G.add_edge(6,5)
G.add_edge(6,4)
G.add_edge(4,5)

In [22]:
G.nodes

NodeView((1, 2, 3, 6, 5, 4))

In [0]:
A = nx.adjacency_matrix(G)

In [24]:
print(A.todense())

[[0 1 1 0 0 0]
 [1 0 1 0 0 0]
 [1 1 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]]


In [0]:
D = np.zeros((len(G.nodes), len(G.nodes)))  

In [26]:
indexer = 0
for node in G.nodes:
  D[indexer][indexer] = G.degree(node)
  indexer += 1
print(D)
print(G.degree(6))

[[2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2.]]
2


In [0]:
L = D - A

In [28]:
L

matrix([[ 2., -1., -1.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  0.,  0.],
        [-1., -1.,  2.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2., -1., -1.],
        [ 0.,  0.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0., -1., -1.,  2.]])

In [0]:
for rowidx in range(L.shape[0]):
  L[rowidx] = L[rowidx]/float(L[rowidx, rowidx])

In [30]:
L

matrix([[ 1. , -0.5, -0.5,  0. ,  0. ,  0. ],
        [-0.5,  1. , -0.5,  0. ,  0. ,  0. ],
        [-0.5, -0.5,  1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  1. , -0.5, -0.5],
        [ 0. ,  0. ,  0. , -0.5,  1. , -0.5],
        [ 0. ,  0. ,  0. , -0.5, -0.5,  1. ]])

In [31]:
L.item((1,1))

1.0

In [0]:
eigvals,eigvecs = np.linalg.eig(L)

In [33]:

eigvecs

matrix([[ 0.81649658, -0.57735027,  0.29329423,  0.        ,  0.        ,
          0.        ],
        [-0.40824829, -0.57735027, -0.80655913,  0.        ,  0.        ,
          0.        ],
        [-0.40824829, -0.57735027,  0.5132649 ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.81649658, -0.57735027,
          0.29329423],
        [ 0.        ,  0.        ,  0.        , -0.40824829, -0.57735027,
         -0.80655913],
        [ 0.        ,  0.        ,  0.        , -0.40824829, -0.57735027,
          0.5132649 ]])

In [34]:
eigvals

array([ 1.50000000e+00, -1.11022302e-16,  1.50000000e+00,  1.50000000e+00,
       -1.11022302e-16,  1.50000000e+00])

In [0]:
num_clusters = 2

In [0]:
selected_eigvecs = []
while len(selected_eigvecs) < num_clusters:
  idx = np.where(eigvals == min(eigvals))
  for i in idx[0]:
    selected_eigvecs.append(np.array(eigvecs[i])[0])
    if len(selected_eigvecs) == num_clusters:
      break
selected_eigvecs = np.array(selected_eigvecs)

In [85]:
nodes = []
for i in range(len(G.nodes)):
  nodes.append(selected_eigvecs[:, i])
nodes

[array([-0.40824829,  0.        ]),
 array([-0.57735027,  0.        ]),
 array([-0.80655913,  0.        ]),
 array([ 0.        , -0.40824829]),
 array([ 0.        , -0.57735027]),
 array([ 0.        , -0.80655913])]

In [0]:
kmeans = KMeans(n_clusters=2, init = 'k-means++').fit(nodes)

In [87]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

array([[-0.40824829, -0.57735027, -0.80655913,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        , -0.40824829, -0.57735027,
        -0.80655913]])

array([-0.57735027,  0.        ])